# Generated by Django 5.1.2 on 2024-11-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="simple one-line text",
                        max_length=100,
                        verbose_name="DESCRIPTION",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="TITLE")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="simple one = line text",
                        max_length=100,
                        verbose_name="DESCRIPTION",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/%Y/%m",
                        verbose_name="IMAGE",
                    ),
                ),
                ("contente", models.TextField(verbose_name="CONTENT")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="CREATE DT"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                ("like", models.PositiveIntegerField(default=0, verbose_name="LIKE")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="CONTENT")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="CRATE DT"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="UPDATE DT"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
            ],
        ),
    ]
